### ISSUE TITLE
sbt fails to load project

### ISSUE THREAD

**Issue by psuter** [heathermiller/f-p#13]
Loading fails with error:

```
error: not found: value EclipseKeys
```

Adding

```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")
```

to `project/plugins.sbt` fixes the issue.

**Comment by francisdb** [comment]
In general it's a better idea to not pollute projects with this plugin. You can easily add that to all your projects by adding the plugin and config here:
`~/.sbt/0.13/plugins/plugins.sbt`
`~/.sbt/0.13/global.sbt`

**Comment by psuter** [comment]
Thanks for the tip, that sounds like a better approach indeed.

**Comment by francisdb** [comment]
@psuter This is not fixed, I was talking to the project maintainers ;-)

they seem to be somehow aware of the issue according to:
https://github.com/heathermiller/f-p/blob/master/eclipse.sbt
